### PR TITLE
Use --depth=1 to speed up git clones of large repositories

### PR DESCRIPTION
**Pull request by jxltom**
This PR adds ```--depth=1``` to make cloning faster

### CODE REVIEW

**Review by dmathieu — CHANGES_REQUESTED** [review]
This is a very good idea, thank you.

The thing with `--depth=1` is that we may not have the branch we checkout into at line 30.
This can be fixed by passing the branch name with the `-b` parameter, if we have a branch. Could you do that?
You can also add the `--single-branch` flag.

**Review by dmathieu — APPROVED** [review]

**Comment by jxltom** [comment]
@dmathieu Thanks for reminding. I have updated the PR, please review. Thanks.

**Comment by jughead** [comment]
This breaks the tags with the specific commit hashes.

**Comment by edmorley** [comment]
@jughead Ah thank you. I'd checked https://www.git-scm.com/docs/git-clone#Documentation/git-clone.txt---branchltnamegt which says:

> --branch can also take tags and detaches the HEAD at that commit in the resulting repository

...but I guess it literally means tags, and not "any git ref".

**Comment by edmorley** [comment]
Reverted in #18 - thank you for letting us know :-)

**Pull request merged**
